language: csharp
mono: none
dotnet: 2.2
script:
 - dotnet restore
 - dotnet publish
deploy:
 provider: heroku
 api_key:
   secure: "XRB60QhOisjqLj3fhLCmkm3q4cqt3b8bdHSEzvhz8Z0L4S372NDjwxCLGNoMnBWaJJ0H+8GRaACiESVmyYq4XpuKk8ap6PWse7Pd37oSdcg+K0vTvqseBICI8APQvU444xXmpp3w3ZasbefOX7kY2Lt0C3NK4MHXgTsb9mQJq8kflBlZ+wGBnOFz3rkNEVxPZeQeDCzsUrjoEQpYj7yHdGQguPbIGfi1qanpy8QGrclcsFfMfFxExarJO5VLoh2Xy7HFjJu6NMO7BYy8o0pIJHPm/ummB+EvAiWYaGf0Q3jq6iD5bJC0NbysL7EHPm+apx9VUqjKVD5vAS+NZ8BZLd5Em+n1RlML69YvBDv7XiXEXYXjyxsNoYX7Z6Oxk4KA6WOGq8aiWrjKo7HOJYjg//7C6XPvLSoQNl84BYn8fxCn1gV4u/vjEx+uKj9VZKmor+ibBgR0klJNMYHsikSeVO9dH5/2H0qlm05RVz1ecE4rQ93pgc/KV/PAGohkh4UxzsbPSZhVUBeflr5mM49j708FtHf/8+GWxing9F3oGP4MVzJJNmeZpKkSbnqQlw9VKrLkOZoDThu/gaI8oqNeD+6wvDJTNUL3sMjx9jnkWPNconUgBXCG4hysJKXTCBF0chV9eDRJ/H8nDAbeSZ07ohoeKXgrVxU/vMEyk6WZ+RY="
 app: gamerpals-backend