language: csharp
mono: none
dotnet: 2.2
script:
 - dotnet restore
 - dotnet publish
deploy:
 provider: heroku
 api_key:
   secure: "O+wSR1LcUeIiaOI5O5P9VhLjAFkrsE8upSOVmXrt2lUAgbHLq9lKYemX0B12YjBl1XP67Ig1etYDt7gK0ePZXOQC04eE+WcYP6hoBIHqhOoZbsnqRIIP89asU0u7htWOQUNM+DQYBl6RzBCnk+25+g1l+RwZXwIWlAxy9FPeR/UYeNHm/4xBBMBOAWIILro+L+owGDsgR7nPvQZVLL8HnzO5ZdIaujf/BKeBXMqfpX2f07KN0fiqWWPRBGT2BFUGhZDmuxAhqVrJQu3jDhtxyPlMSQSIYbsHVcIAXK9gend0X820joIx9bHWvelT65LJjPbf+kf5OM5ngsrQYSYPJnOnvsJ0vtjPS7sRI0jWWs8k4i39oRul8hCYfr3JsR3LAQpt+1+AhH203WTwwR5UYw5VkM64oxBY8tAdyM9aRoaNOm0To67WBoyTbsI6hUp7kih7gf4xh075eATPCBmZmAPypy/ykOIH6tKkpk3gCd0XRNJwWe2wtY1oOKAWYi9d72MN6OyXjAIPoXG0i46WjyToArhmzaxLMM/KlqEzxv88VaCV9uTNp9mO8zR9v620KSthijI8pxo1zfKL8s16HGLNCsGAqxKqOC2IM4+IDUwXfmwHDYq4Lq26rBVSaeHud4XkqNJ9jMfeqj4zIq7Py0WVmb9vb+dHTS4sJ2aBQa8="
 app: gamerpals-backend