SET IDENTITY_INSERT [dbo].[Servers] ON
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (1, 4, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (2, 5, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (3, 6, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (7, 8, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (8, 9, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (9, 10, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (10, 11, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (11, 12, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (12, 13, N'EUW')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (13, 4, N'NA')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (14, 5, N'NA')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (15, 6, N'NA')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (16, 8, N'NA')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (17, 9, N'NA')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (18, 10, N'NA')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (19, 11, N'NA')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (20, 12, N'NA')
INSERT INTO [dbo].[Servers] ([GameServerID], [ServerGameGameID], [ServerName]) VALUES (21, 13, N'NA')
SET IDENTITY_INSERT [dbo].[Servers] OFF
