// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using GamerPalsBackend.DataObjects.Models;

namespace GamerPalsBackend.Migrations
{
    [DbContext(typeof(PalsContext))]
    [Migration("20180818155451_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GamerPalsBackend.Models.ActiveSearch", b =>
                {
                    b.Property<int>("ActiveSearchID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("MaxPlayers");

                    b.Property<int?>("SearchTypeID");

                    b.Property<int?>("ServerGameServerID");

                    b.HasKey("ActiveSearchID");

                    b.HasIndex("SearchTypeID");

                    b.HasIndex("ServerGameServerID");

                    b.ToTable("ActiveSearches");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentSearch");

                    b.Property<string>("GameName");

                    b.Property<int>("PlayersOnline");

                    b.Property<int?>("UserID");

                    b.HasKey("GameID");

                    b.HasIndex("UserID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.GameServer", b =>
                {
                    b.Property<int>("GameServerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ServerGameGameID");

                    b.Property<string>("ServerName");

                    b.HasKey("GameServerID");

                    b.HasIndex("ServerGameGameID");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActiveSearchID");

                    b.Property<int?>("LeaderUserID");

                    b.HasKey("GroupID");

                    b.HasIndex("ActiveSearchID");

                    b.HasIndex("LeaderUserID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LangLong");

                    b.Property<string>("LangShort");

                    b.Property<int?>("UserID");

                    b.HasKey("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.Parameter", b =>
                {
                    b.Property<int>("ParameterID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameID");

                    b.Property<string>("ParameterName");

                    b.Property<string>("ParameterValue");

                    b.HasKey("ParameterID");

                    b.HasIndex("GameID");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.SearchSettings", b =>
                {
                    b.Property<int>("SearchSettingsID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActiveSearchID");

                    b.Property<int?>("ParameterID");

                    b.HasKey("SearchSettingsID");

                    b.HasIndex("ActiveSearchID");

                    b.HasIndex("ParameterID");

                    b.ToTable("SearchSettings");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.SearchType", b =>
                {
                    b.Property<int>("SearchTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SearchTypeName");

                    b.HasKey("SearchTypeID");

                    b.ToTable("SearchTypes");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActiveSearchID");

                    b.Property<byte>("Age");

                    b.Property<string>("Country");

                    b.Property<int>("FacebookID");

                    b.Property<byte>("Gender");

                    b.Property<int>("GoogleID");

                    b.Property<int>("Karma");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.HasIndex("ActiveSearchID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.ActiveSearch", b =>
                {
                    b.HasOne("GamerPalsBackend.Models.SearchType", "SearchType")
                        .WithMany()
                        .HasForeignKey("SearchTypeID");

                    b.HasOne("GamerPalsBackend.Models.GameServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerGameServerID");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.Game", b =>
                {
                    b.HasOne("GamerPalsBackend.Models.User")
                        .WithMany("Games")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.GameServer", b =>
                {
                    b.HasOne("GamerPalsBackend.Models.Game", "ServerGame")
                        .WithMany("Servers")
                        .HasForeignKey("ServerGameGameID");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.Group", b =>
                {
                    b.HasOne("GamerPalsBackend.Models.ActiveSearch", "ActiveSearch")
                        .WithMany()
                        .HasForeignKey("ActiveSearchID");

                    b.HasOne("GamerPalsBackend.Models.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderUserID");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.Language", b =>
                {
                    b.HasOne("GamerPalsBackend.Models.User")
                        .WithMany("Languages")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.Parameter", b =>
                {
                    b.HasOne("GamerPalsBackend.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.SearchSettings", b =>
                {
                    b.HasOne("GamerPalsBackend.Models.ActiveSearch")
                        .WithMany("Settings")
                        .HasForeignKey("ActiveSearchID");

                    b.HasOne("GamerPalsBackend.Models.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterID");
                });

            modelBuilder.Entity("GamerPalsBackend.Models.User", b =>
                {
                    b.HasOne("GamerPalsBackend.Models.ActiveSearch")
                        .WithMany("JoinedUsers")
                        .HasForeignKey("ActiveSearchID");
                });
#pragma warning restore 612, 618
        }
    }
}
